# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1faff5e53780b629d731683bb36e90bb254f0df869c78e5fbf92e1091358c229690d8b5659e89d7b1947a9d4cf6f82805b9d56355cff95286f8ba5dad1703a6

test:
  secret_key_base: 4ddf714a652e16c1b798ba8a5bd4cd77d4bab8edbcb8e8cd0fe594bb3b27e33fdea26eb8c9dd16cd70f3b27c88535d367cd86afb392d41a64ef8845469ef1f38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
